use_frameworks!

platform :ios, '9.0'

target 'MWTableViewCellSeparatorLine_Example' do
  pod 'MWTableViewCellSeparatorLine', :path => '../'

  target 'MWTableViewCellSeparatorLine_Tests' do
    inherit! :search_paths

    
  end
end
